title: IT Journey
author: Edward-Beltran
email: edward.beltran1@outlook.com
description: > blah blah blah

# social links

github_username:  edward-beltran

show_excerpts: true # set to false to remove excerpts on the homepage
